// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greptime/v1/wal.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_greptime_2fv1_2fwal_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_greptime_2fv1_2fwal_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "greptime/v1/row.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_greptime_2fv1_2fwal_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_greptime_2fv1_2fwal_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_greptime_2fv1_2fwal_2eproto;
namespace greptime {
namespace v1 {
class ManifestAction;
struct ManifestActionDefaultTypeInternal;
extern ManifestActionDefaultTypeInternal _ManifestAction_default_instance_;
class ManifestActionList;
struct ManifestActionListDefaultTypeInternal;
extern ManifestActionListDefaultTypeInternal _ManifestActionList_default_instance_;
class Mutation;
struct MutationDefaultTypeInternal;
extern MutationDefaultTypeInternal _Mutation_default_instance_;
class WalEntry;
struct WalEntryDefaultTypeInternal;
extern WalEntryDefaultTypeInternal _WalEntry_default_instance_;
}  // namespace v1
}  // namespace greptime
PROTOBUF_NAMESPACE_OPEN
template<> ::greptime::v1::ManifestAction* Arena::CreateMaybeMessage<::greptime::v1::ManifestAction>(Arena*);
template<> ::greptime::v1::ManifestActionList* Arena::CreateMaybeMessage<::greptime::v1::ManifestActionList>(Arena*);
template<> ::greptime::v1::Mutation* Arena::CreateMaybeMessage<::greptime::v1::Mutation>(Arena*);
template<> ::greptime::v1::WalEntry* Arena::CreateMaybeMessage<::greptime::v1::WalEntry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace greptime {
namespace v1 {

enum OpType : int {
  DELETE = 0,
  PUT = 1,
  MANIFEST = 2,
  OpType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  OpType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool OpType_IsValid(int value);
constexpr OpType OpType_MIN = DELETE;
constexpr OpType OpType_MAX = MANIFEST;
constexpr int OpType_ARRAYSIZE = OpType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OpType_descriptor();
template<typename T>
inline const std::string& OpType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, OpType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function OpType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    OpType_descriptor(), enum_t_value);
}
inline bool OpType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, OpType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<OpType>(
    OpType_descriptor(), name, value);
}
// ===================================================================

class ManifestAction final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:greptime.v1.ManifestAction) */ {
 public:
  inline ManifestAction() : ManifestAction(nullptr) {}
  ~ManifestAction() override;
  explicit PROTOBUF_CONSTEXPR ManifestAction(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ManifestAction(const ManifestAction& from);
  ManifestAction(ManifestAction&& from) noexcept
    : ManifestAction() {
    *this = ::std::move(from);
  }

  inline ManifestAction& operator=(const ManifestAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline ManifestAction& operator=(ManifestAction&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ManifestAction& default_instance() {
    return *internal_default_instance();
  }
  enum DataCase {
    kJson = 1,
    DATA_NOT_SET = 0,
  };

  static inline const ManifestAction* internal_default_instance() {
    return reinterpret_cast<const ManifestAction*>(
               &_ManifestAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ManifestAction& a, ManifestAction& b) {
    a.Swap(&b);
  }
  inline void Swap(ManifestAction* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ManifestAction* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ManifestAction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ManifestAction>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ManifestAction& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ManifestAction& from) {
    ManifestAction::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ManifestAction* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "greptime.v1.ManifestAction";
  }
  protected:
  explicit ManifestAction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJsonFieldNumber = 1,
  };
  // string json = 1;
  bool has_json() const;
  private:
  bool _internal_has_json() const;
  public:
  void clear_json();
  const std::string& json() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_json(ArgT0&& arg0, ArgT... args);
  std::string* mutable_json();
  PROTOBUF_NODISCARD std::string* release_json();
  void set_allocated_json(std::string* json);
  private:
  const std::string& _internal_json() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_json(const std::string& value);
  std::string* _internal_mutable_json();
  public:

  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:greptime.v1.ManifestAction)
 private:
  class _Internal;
  void set_has_json();

  inline bool has_data() const;
  inline void clear_has_data();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union DataUnion {
      constexpr DataUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr json_;
    } data_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_greptime_2fv1_2fwal_2eproto;
};
// -------------------------------------------------------------------

class ManifestActionList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:greptime.v1.ManifestActionList) */ {
 public:
  inline ManifestActionList() : ManifestActionList(nullptr) {}
  ~ManifestActionList() override;
  explicit PROTOBUF_CONSTEXPR ManifestActionList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ManifestActionList(const ManifestActionList& from);
  ManifestActionList(ManifestActionList&& from) noexcept
    : ManifestActionList() {
    *this = ::std::move(from);
  }

  inline ManifestActionList& operator=(const ManifestActionList& from) {
    CopyFrom(from);
    return *this;
  }
  inline ManifestActionList& operator=(ManifestActionList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ManifestActionList& default_instance() {
    return *internal_default_instance();
  }
  static inline const ManifestActionList* internal_default_instance() {
    return reinterpret_cast<const ManifestActionList*>(
               &_ManifestActionList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ManifestActionList& a, ManifestActionList& b) {
    a.Swap(&b);
  }
  inline void Swap(ManifestActionList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ManifestActionList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ManifestActionList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ManifestActionList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ManifestActionList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ManifestActionList& from) {
    ManifestActionList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ManifestActionList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "greptime.v1.ManifestActionList";
  }
  protected:
  explicit ManifestActionList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActionsFieldNumber = 2,
    kManifestVersionFieldNumber = 1,
  };
  // repeated .greptime.v1.ManifestAction actions = 2;
  int actions_size() const;
  private:
  int _internal_actions_size() const;
  public:
  void clear_actions();
  ::greptime::v1::ManifestAction* mutable_actions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::greptime::v1::ManifestAction >*
      mutable_actions();
  private:
  const ::greptime::v1::ManifestAction& _internal_actions(int index) const;
  ::greptime::v1::ManifestAction* _internal_add_actions();
  public:
  const ::greptime::v1::ManifestAction& actions(int index) const;
  ::greptime::v1::ManifestAction* add_actions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::greptime::v1::ManifestAction >&
      actions() const;

  // uint64 manifest_version = 1;
  void clear_manifest_version();
  uint64_t manifest_version() const;
  void set_manifest_version(uint64_t value);
  private:
  uint64_t _internal_manifest_version() const;
  void _internal_set_manifest_version(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:greptime.v1.ManifestActionList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::greptime::v1::ManifestAction > actions_;
    uint64_t manifest_version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_greptime_2fv1_2fwal_2eproto;
};
// -------------------------------------------------------------------

class Mutation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:greptime.v1.Mutation) */ {
 public:
  inline Mutation() : Mutation(nullptr) {}
  ~Mutation() override;
  explicit PROTOBUF_CONSTEXPR Mutation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Mutation(const Mutation& from);
  Mutation(Mutation&& from) noexcept
    : Mutation() {
    *this = ::std::move(from);
  }

  inline Mutation& operator=(const Mutation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Mutation& operator=(Mutation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Mutation& default_instance() {
    return *internal_default_instance();
  }
  static inline const Mutation* internal_default_instance() {
    return reinterpret_cast<const Mutation*>(
               &_Mutation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Mutation& a, Mutation& b) {
    a.Swap(&b);
  }
  inline void Swap(Mutation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Mutation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Mutation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Mutation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Mutation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Mutation& from) {
    Mutation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Mutation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "greptime.v1.Mutation";
  }
  protected:
  explicit Mutation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRowsFieldNumber = 3,
    kActionListFieldNumber = 4,
    kSequenceFieldNumber = 2,
    kOpTypeFieldNumber = 1,
  };
  // .greptime.v1.Rows rows = 3;
  bool has_rows() const;
  private:
  bool _internal_has_rows() const;
  public:
  void clear_rows();
  const ::greptime::v1::Rows& rows() const;
  PROTOBUF_NODISCARD ::greptime::v1::Rows* release_rows();
  ::greptime::v1::Rows* mutable_rows();
  void set_allocated_rows(::greptime::v1::Rows* rows);
  private:
  const ::greptime::v1::Rows& _internal_rows() const;
  ::greptime::v1::Rows* _internal_mutable_rows();
  public:
  void unsafe_arena_set_allocated_rows(
      ::greptime::v1::Rows* rows);
  ::greptime::v1::Rows* unsafe_arena_release_rows();

  // .greptime.v1.ManifestActionList action_list = 4;
  bool has_action_list() const;
  private:
  bool _internal_has_action_list() const;
  public:
  void clear_action_list();
  const ::greptime::v1::ManifestActionList& action_list() const;
  PROTOBUF_NODISCARD ::greptime::v1::ManifestActionList* release_action_list();
  ::greptime::v1::ManifestActionList* mutable_action_list();
  void set_allocated_action_list(::greptime::v1::ManifestActionList* action_list);
  private:
  const ::greptime::v1::ManifestActionList& _internal_action_list() const;
  ::greptime::v1::ManifestActionList* _internal_mutable_action_list();
  public:
  void unsafe_arena_set_allocated_action_list(
      ::greptime::v1::ManifestActionList* action_list);
  ::greptime::v1::ManifestActionList* unsafe_arena_release_action_list();

  // uint64 sequence = 2;
  void clear_sequence();
  uint64_t sequence() const;
  void set_sequence(uint64_t value);
  private:
  uint64_t _internal_sequence() const;
  void _internal_set_sequence(uint64_t value);
  public:

  // .greptime.v1.OpType op_type = 1;
  void clear_op_type();
  ::greptime::v1::OpType op_type() const;
  void set_op_type(::greptime::v1::OpType value);
  private:
  ::greptime::v1::OpType _internal_op_type() const;
  void _internal_set_op_type(::greptime::v1::OpType value);
  public:

  // @@protoc_insertion_point(class_scope:greptime.v1.Mutation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::greptime::v1::Rows* rows_;
    ::greptime::v1::ManifestActionList* action_list_;
    uint64_t sequence_;
    int op_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_greptime_2fv1_2fwal_2eproto;
};
// -------------------------------------------------------------------

class WalEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:greptime.v1.WalEntry) */ {
 public:
  inline WalEntry() : WalEntry(nullptr) {}
  ~WalEntry() override;
  explicit PROTOBUF_CONSTEXPR WalEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WalEntry(const WalEntry& from);
  WalEntry(WalEntry&& from) noexcept
    : WalEntry() {
    *this = ::std::move(from);
  }

  inline WalEntry& operator=(const WalEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline WalEntry& operator=(WalEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WalEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const WalEntry* internal_default_instance() {
    return reinterpret_cast<const WalEntry*>(
               &_WalEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(WalEntry& a, WalEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(WalEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WalEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WalEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<WalEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WalEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const WalEntry& from) {
    WalEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WalEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "greptime.v1.WalEntry";
  }
  protected:
  explicit WalEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMutationsFieldNumber = 1,
  };
  // repeated .greptime.v1.Mutation mutations = 1;
  int mutations_size() const;
  private:
  int _internal_mutations_size() const;
  public:
  void clear_mutations();
  ::greptime::v1::Mutation* mutable_mutations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::greptime::v1::Mutation >*
      mutable_mutations();
  private:
  const ::greptime::v1::Mutation& _internal_mutations(int index) const;
  ::greptime::v1::Mutation* _internal_add_mutations();
  public:
  const ::greptime::v1::Mutation& mutations(int index) const;
  ::greptime::v1::Mutation* add_mutations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::greptime::v1::Mutation >&
      mutations() const;

  // @@protoc_insertion_point(class_scope:greptime.v1.WalEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::greptime::v1::Mutation > mutations_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_greptime_2fv1_2fwal_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ManifestAction

// string json = 1;
inline bool ManifestAction::_internal_has_json() const {
  return data_case() == kJson;
}
inline bool ManifestAction::has_json() const {
  return _internal_has_json();
}
inline void ManifestAction::set_has_json() {
  _impl_._oneof_case_[0] = kJson;
}
inline void ManifestAction::clear_json() {
  if (_internal_has_json()) {
    _impl_.data_.json_.Destroy();
    clear_has_data();
  }
}
inline const std::string& ManifestAction::json() const {
  // @@protoc_insertion_point(field_get:greptime.v1.ManifestAction.json)
  return _internal_json();
}
template <typename ArgT0, typename... ArgT>
inline void ManifestAction::set_json(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_json()) {
    clear_data();
    set_has_json();
    _impl_.data_.json_.InitDefault();
  }
  _impl_.data_.json_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:greptime.v1.ManifestAction.json)
}
inline std::string* ManifestAction::mutable_json() {
  std::string* _s = _internal_mutable_json();
  // @@protoc_insertion_point(field_mutable:greptime.v1.ManifestAction.json)
  return _s;
}
inline const std::string& ManifestAction::_internal_json() const {
  if (_internal_has_json()) {
    return _impl_.data_.json_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void ManifestAction::_internal_set_json(const std::string& value) {
  if (!_internal_has_json()) {
    clear_data();
    set_has_json();
    _impl_.data_.json_.InitDefault();
  }
  _impl_.data_.json_.Set(value, GetArenaForAllocation());
}
inline std::string* ManifestAction::_internal_mutable_json() {
  if (!_internal_has_json()) {
    clear_data();
    set_has_json();
    _impl_.data_.json_.InitDefault();
  }
  return _impl_.data_.json_.Mutable(      GetArenaForAllocation());
}
inline std::string* ManifestAction::release_json() {
  // @@protoc_insertion_point(field_release:greptime.v1.ManifestAction.json)
  if (_internal_has_json()) {
    clear_has_data();
    return _impl_.data_.json_.Release();
  } else {
    return nullptr;
  }
}
inline void ManifestAction::set_allocated_json(std::string* json) {
  if (has_data()) {
    clear_data();
  }
  if (json != nullptr) {
    set_has_json();
    _impl_.data_.json_.InitAllocated(json, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:greptime.v1.ManifestAction.json)
}

inline bool ManifestAction::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void ManifestAction::clear_has_data() {
  _impl_._oneof_case_[0] = DATA_NOT_SET;
}
inline ManifestAction::DataCase ManifestAction::data_case() const {
  return ManifestAction::DataCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ManifestActionList

// uint64 manifest_version = 1;
inline void ManifestActionList::clear_manifest_version() {
  _impl_.manifest_version_ = uint64_t{0u};
}
inline uint64_t ManifestActionList::_internal_manifest_version() const {
  return _impl_.manifest_version_;
}
inline uint64_t ManifestActionList::manifest_version() const {
  // @@protoc_insertion_point(field_get:greptime.v1.ManifestActionList.manifest_version)
  return _internal_manifest_version();
}
inline void ManifestActionList::_internal_set_manifest_version(uint64_t value) {
  
  _impl_.manifest_version_ = value;
}
inline void ManifestActionList::set_manifest_version(uint64_t value) {
  _internal_set_manifest_version(value);
  // @@protoc_insertion_point(field_set:greptime.v1.ManifestActionList.manifest_version)
}

// repeated .greptime.v1.ManifestAction actions = 2;
inline int ManifestActionList::_internal_actions_size() const {
  return _impl_.actions_.size();
}
inline int ManifestActionList::actions_size() const {
  return _internal_actions_size();
}
inline void ManifestActionList::clear_actions() {
  _impl_.actions_.Clear();
}
inline ::greptime::v1::ManifestAction* ManifestActionList::mutable_actions(int index) {
  // @@protoc_insertion_point(field_mutable:greptime.v1.ManifestActionList.actions)
  return _impl_.actions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::greptime::v1::ManifestAction >*
ManifestActionList::mutable_actions() {
  // @@protoc_insertion_point(field_mutable_list:greptime.v1.ManifestActionList.actions)
  return &_impl_.actions_;
}
inline const ::greptime::v1::ManifestAction& ManifestActionList::_internal_actions(int index) const {
  return _impl_.actions_.Get(index);
}
inline const ::greptime::v1::ManifestAction& ManifestActionList::actions(int index) const {
  // @@protoc_insertion_point(field_get:greptime.v1.ManifestActionList.actions)
  return _internal_actions(index);
}
inline ::greptime::v1::ManifestAction* ManifestActionList::_internal_add_actions() {
  return _impl_.actions_.Add();
}
inline ::greptime::v1::ManifestAction* ManifestActionList::add_actions() {
  ::greptime::v1::ManifestAction* _add = _internal_add_actions();
  // @@protoc_insertion_point(field_add:greptime.v1.ManifestActionList.actions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::greptime::v1::ManifestAction >&
ManifestActionList::actions() const {
  // @@protoc_insertion_point(field_list:greptime.v1.ManifestActionList.actions)
  return _impl_.actions_;
}

// -------------------------------------------------------------------

// Mutation

// .greptime.v1.OpType op_type = 1;
inline void Mutation::clear_op_type() {
  _impl_.op_type_ = 0;
}
inline ::greptime::v1::OpType Mutation::_internal_op_type() const {
  return static_cast< ::greptime::v1::OpType >(_impl_.op_type_);
}
inline ::greptime::v1::OpType Mutation::op_type() const {
  // @@protoc_insertion_point(field_get:greptime.v1.Mutation.op_type)
  return _internal_op_type();
}
inline void Mutation::_internal_set_op_type(::greptime::v1::OpType value) {
  
  _impl_.op_type_ = value;
}
inline void Mutation::set_op_type(::greptime::v1::OpType value) {
  _internal_set_op_type(value);
  // @@protoc_insertion_point(field_set:greptime.v1.Mutation.op_type)
}

// uint64 sequence = 2;
inline void Mutation::clear_sequence() {
  _impl_.sequence_ = uint64_t{0u};
}
inline uint64_t Mutation::_internal_sequence() const {
  return _impl_.sequence_;
}
inline uint64_t Mutation::sequence() const {
  // @@protoc_insertion_point(field_get:greptime.v1.Mutation.sequence)
  return _internal_sequence();
}
inline void Mutation::_internal_set_sequence(uint64_t value) {
  
  _impl_.sequence_ = value;
}
inline void Mutation::set_sequence(uint64_t value) {
  _internal_set_sequence(value);
  // @@protoc_insertion_point(field_set:greptime.v1.Mutation.sequence)
}

// .greptime.v1.Rows rows = 3;
inline bool Mutation::_internal_has_rows() const {
  return this != internal_default_instance() && _impl_.rows_ != nullptr;
}
inline bool Mutation::has_rows() const {
  return _internal_has_rows();
}
inline const ::greptime::v1::Rows& Mutation::_internal_rows() const {
  const ::greptime::v1::Rows* p = _impl_.rows_;
  return p != nullptr ? *p : reinterpret_cast<const ::greptime::v1::Rows&>(
      ::greptime::v1::_Rows_default_instance_);
}
inline const ::greptime::v1::Rows& Mutation::rows() const {
  // @@protoc_insertion_point(field_get:greptime.v1.Mutation.rows)
  return _internal_rows();
}
inline void Mutation::unsafe_arena_set_allocated_rows(
    ::greptime::v1::Rows* rows) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rows_);
  }
  _impl_.rows_ = rows;
  if (rows) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:greptime.v1.Mutation.rows)
}
inline ::greptime::v1::Rows* Mutation::release_rows() {
  
  ::greptime::v1::Rows* temp = _impl_.rows_;
  _impl_.rows_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::greptime::v1::Rows* Mutation::unsafe_arena_release_rows() {
  // @@protoc_insertion_point(field_release:greptime.v1.Mutation.rows)
  
  ::greptime::v1::Rows* temp = _impl_.rows_;
  _impl_.rows_ = nullptr;
  return temp;
}
inline ::greptime::v1::Rows* Mutation::_internal_mutable_rows() {
  
  if (_impl_.rows_ == nullptr) {
    auto* p = CreateMaybeMessage<::greptime::v1::Rows>(GetArenaForAllocation());
    _impl_.rows_ = p;
  }
  return _impl_.rows_;
}
inline ::greptime::v1::Rows* Mutation::mutable_rows() {
  ::greptime::v1::Rows* _msg = _internal_mutable_rows();
  // @@protoc_insertion_point(field_mutable:greptime.v1.Mutation.rows)
  return _msg;
}
inline void Mutation::set_allocated_rows(::greptime::v1::Rows* rows) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rows_);
  }
  if (rows) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rows));
    if (message_arena != submessage_arena) {
      rows = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rows, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.rows_ = rows;
  // @@protoc_insertion_point(field_set_allocated:greptime.v1.Mutation.rows)
}

// .greptime.v1.ManifestActionList action_list = 4;
inline bool Mutation::_internal_has_action_list() const {
  return this != internal_default_instance() && _impl_.action_list_ != nullptr;
}
inline bool Mutation::has_action_list() const {
  return _internal_has_action_list();
}
inline void Mutation::clear_action_list() {
  if (GetArenaForAllocation() == nullptr && _impl_.action_list_ != nullptr) {
    delete _impl_.action_list_;
  }
  _impl_.action_list_ = nullptr;
}
inline const ::greptime::v1::ManifestActionList& Mutation::_internal_action_list() const {
  const ::greptime::v1::ManifestActionList* p = _impl_.action_list_;
  return p != nullptr ? *p : reinterpret_cast<const ::greptime::v1::ManifestActionList&>(
      ::greptime::v1::_ManifestActionList_default_instance_);
}
inline const ::greptime::v1::ManifestActionList& Mutation::action_list() const {
  // @@protoc_insertion_point(field_get:greptime.v1.Mutation.action_list)
  return _internal_action_list();
}
inline void Mutation::unsafe_arena_set_allocated_action_list(
    ::greptime::v1::ManifestActionList* action_list) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.action_list_);
  }
  _impl_.action_list_ = action_list;
  if (action_list) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:greptime.v1.Mutation.action_list)
}
inline ::greptime::v1::ManifestActionList* Mutation::release_action_list() {
  
  ::greptime::v1::ManifestActionList* temp = _impl_.action_list_;
  _impl_.action_list_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::greptime::v1::ManifestActionList* Mutation::unsafe_arena_release_action_list() {
  // @@protoc_insertion_point(field_release:greptime.v1.Mutation.action_list)
  
  ::greptime::v1::ManifestActionList* temp = _impl_.action_list_;
  _impl_.action_list_ = nullptr;
  return temp;
}
inline ::greptime::v1::ManifestActionList* Mutation::_internal_mutable_action_list() {
  
  if (_impl_.action_list_ == nullptr) {
    auto* p = CreateMaybeMessage<::greptime::v1::ManifestActionList>(GetArenaForAllocation());
    _impl_.action_list_ = p;
  }
  return _impl_.action_list_;
}
inline ::greptime::v1::ManifestActionList* Mutation::mutable_action_list() {
  ::greptime::v1::ManifestActionList* _msg = _internal_mutable_action_list();
  // @@protoc_insertion_point(field_mutable:greptime.v1.Mutation.action_list)
  return _msg;
}
inline void Mutation::set_allocated_action_list(::greptime::v1::ManifestActionList* action_list) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.action_list_;
  }
  if (action_list) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(action_list);
    if (message_arena != submessage_arena) {
      action_list = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, action_list, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.action_list_ = action_list;
  // @@protoc_insertion_point(field_set_allocated:greptime.v1.Mutation.action_list)
}

// -------------------------------------------------------------------

// WalEntry

// repeated .greptime.v1.Mutation mutations = 1;
inline int WalEntry::_internal_mutations_size() const {
  return _impl_.mutations_.size();
}
inline int WalEntry::mutations_size() const {
  return _internal_mutations_size();
}
inline void WalEntry::clear_mutations() {
  _impl_.mutations_.Clear();
}
inline ::greptime::v1::Mutation* WalEntry::mutable_mutations(int index) {
  // @@protoc_insertion_point(field_mutable:greptime.v1.WalEntry.mutations)
  return _impl_.mutations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::greptime::v1::Mutation >*
WalEntry::mutable_mutations() {
  // @@protoc_insertion_point(field_mutable_list:greptime.v1.WalEntry.mutations)
  return &_impl_.mutations_;
}
inline const ::greptime::v1::Mutation& WalEntry::_internal_mutations(int index) const {
  return _impl_.mutations_.Get(index);
}
inline const ::greptime::v1::Mutation& WalEntry::mutations(int index) const {
  // @@protoc_insertion_point(field_get:greptime.v1.WalEntry.mutations)
  return _internal_mutations(index);
}
inline ::greptime::v1::Mutation* WalEntry::_internal_add_mutations() {
  return _impl_.mutations_.Add();
}
inline ::greptime::v1::Mutation* WalEntry::add_mutations() {
  ::greptime::v1::Mutation* _add = _internal_add_mutations();
  // @@protoc_insertion_point(field_add:greptime.v1.WalEntry.mutations)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::greptime::v1::Mutation >&
WalEntry::mutations() const {
  // @@protoc_insertion_point(field_list:greptime.v1.WalEntry.mutations)
  return _impl_.mutations_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace greptime

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::greptime::v1::OpType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::greptime::v1::OpType>() {
  return ::greptime::v1::OpType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_greptime_2fv1_2fwal_2eproto
